#!/bin/python3

import sys


N = int(input().strip())
if(N%2 != 0):
    print("Wierd")
else:
    if N in range(2,5):
        print("Not Wierd")
    elif N in range(6,20):
        print("Wierd")
    elif (N>20):
        print("Not Wierd")
        
